<script>
    // Libs and utils
	import { fade }             from 'svelte/transition';

    // Components
    import DataNoteCW193        from './DataNote_CW193.svelte';
    import Acknowledgements     from './Acknowledgements.svelte';

    // Props
    let {isSideGuide = false} = $props()
</script>

<!-- HTML MARKUP-->
<article class = 'sonification-note' class:isSideGuide={isSideGuide} in:fade>
    <div class = 'content-wrapper' >
        <h1 class = 'header'>// Sonification notes</h1>

        <DataNoteCW193/>

        <section>
            <h2>// Instrument parameter mapping</h2>
            <p>This data instrument features a main, a multi-voice synth setup whose main parameters are controlled by separate data series assigned to tracks A and B; in addition to two drum kit layers (C1 and C2) and a chord instrument (C3). The synth is a (very imperfect) version of the <a href = 'https://www.moogmusic.com/synthesizers/dfam/' target = '_blank'>Moog's DFAM hardware synth</a>.
            </p>
            <ul>
                <li> The tempo of each project is initially mapped to each nation's 'climate risk index', with those at higher risk having a more urgent tempo.
                </li>

                <li>Pitch (notes) on lead and bass synths are mapped to user selectable data series, to produce 16 step note sequences (over one bar).  All data mapped to pitch is has been quantized to scale degrees (covering two octaves for lead and one octave for bass), that are subsequently mapped to the user selectable musical scales.
                    <ul>
                        <li>The selected data series for pitch is set to 'net GHG per capita' by default and is user selectable.</li>
                        <li>The pulse sequences  randomised from within selected euclidean pulse ranges.</li>
                    </ul>
                </li>

                <li>Velocity is mapped to the second user selectable data series (B): by default this is set to the volume of electricity generated by coal (black and brown). Velocity controls not only note volume, but is used in the synth to control a series of envelopes (pitch, amplitude and filter). This introduces somewhat chaotic rhythmic and timbral variations.</li>


                <li>Velocity is mapped to the second user selectable data series (B): by default this is set to the volume of electricity generated by coal (black and brown). Velocity controls not only note volume, but is used in the synth to control a series of envelopes (pitch, amplitude and filter). This introduces somewhat chaotic rhythmic and timbral variations.</li>
                
                <li>The chord layer uses a progression mapped to the same data series as the lead synth. This is scaled to a basic four chord progression that follows the chosen musical scale of composition with a lower note resolution (of 4n). By default, this is set to play over 4 bars.</li>

                <li>Drum kit patterns (separated across C1 and C2) are selected presets (10 for each), with drum sounds sampled from the Roland TR-909 drum machine.
                    <ul>
                        <li>The volume (velocity) of hats/metal percussion on track C2 tracks the data for track B, which mirrors the volume of the main synth. </li>
                    </ul>
                </li>
            </ul>
        </section>

        <!-- <DataContextPlaceholder/> -->
        <Acknowledgements/>
    </div>
</article>

