<script>
    // Libs and utils
	import { fade }         from 'svelte/transition';

    // Parts
    import DataNoteOE10     from './DataNote_OE10.svelte';
    import Acknowledgements from './Acknowledgements.svelte';

    // Props
    let {isSideGuide = false} = $props()
</script>

<!-- HTML MARKUP-->
<article class:isSideGuide={isSideGuide} in:fade>
    <div class = 'content-wrapper' >
        <h1 class = 'header'>Sonification summary </h1>

        <DataNoteOE10/>

        <section>
            <h2>DFAM: Instrumentation &times; parameter mapping</h2>
            <p>The OE-10:DFAM uses a multi-voice synth setup whose voices are controlled across track A and B; in addition to two drum kit layers (C1 and C2) and a chord instrument (C3). The synth is a (very imperfect) version of the <a href = 'https://www.moogmusic.com/synthesizers/dfam/' target = '_blank'>Moog DFAM </a>.</p>
            <ul>
                <li>Pitch (notes) on the synth is mapped to a user selected data series (A). By default this is assigned to 'electricity market price' and  produces 16 step note sequences that pulses on a change of note (i.e. when the scale-quantized data change is large enough). 
                    <ul>
                        <li>The synth has two oscillators that play the pitches on different octaves, to thicken the sound.</li>
                        <li>The selected data series is also used to set the low pass filter cutoff, and resonance amount. Both of these ranges are mapped to lower resolution data (of 4n, or 6 hour intervals) that change on the same clock as the chord part (C3) (note: this provides some visual feedback as chord changes are displayed in the <i>Data Operator</i> screen)
                        </li>
                    </ul>
                </li>
                <li>Velocity is mapped to the second user selectable data series (Group B): by default this is set to the volume of electricity generated by coal (black and brown). Velocity controls not only note volume, but is used in the synth to control a series of envelopes (pitch, amplitude and filter). This introduces somewhat chatoic rhythmic and timbral variations.</li>
                
                <li>The chord layer uses a progression mapped to the same data series as the lead synth. This is scaled to a basic four chord progression (I, IV, V and VII) that follows the chosen musical scale of composition with a lower note resolution (of 4n, representing 6 hr intervals). By default, this is set to play over 4 bars. The sound source for chords are sampled from various instruments that can be cycled though/selected by the player.</li>

                <li>Drum kit patterns (separated across C1 and C2) are selected presets (10 for each), with drum sounds sampled from the Roland TR-909 drum machine.
                    <ul>
                        <li>The volume (velocity) of hats/metal percussion on track C2 tracks the data for the amount of fossil fuel generated electricity throughout each day. </li>
                    </ul>
                </li>
            </ul>
        </section>


        <Acknowledgements/>
    </div>
</article>



<!-- STYLES-->
<style>
    h1{
        text-align:     end;
        font-family:    'Orbit';
        font-size:      xx-large;
    }
    h2{
        margin-block-end: 0rem;
        font-family:    'Orbit';
        font-size:      large;
    }
    ul{
        padding-inline-start: 1rem;
    }
</style>